# Generated by Django 5.2.6 on 2025-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_mark_returned', 'Set book as returned')]},
        ),
        migrations.AddField(
            model_name='book',
            name='data_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
